[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "a6bdd9920a3fd7523d54c2790964351d8df68384"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "2cde21fca5a8476cf02e0d29440b79420ecabac78ed78618548884d7be501b24"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "e0ae8e1988425737cec3f6c615497f3284d9e771"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "3ca5094dccdab7cdc190a8d429922dcf26587888197d39fd72a241bca0820433"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "3cd2fb12f766ee959993b19d1c546f9b1e3aa868"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "1f53f127e6cf9b339af73f165246c2d51d4f701dbebd17c28ff03470216a62e6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5706c705c0e2334a19a4b3c5e6a1601316f16615"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "1bb7b315bcc9820dedc0e243c2cc75b444987bda98bdc58fe85f4bb94bdf58b9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5706c705c0e2334a19a4b3c5e6a1601316f16615"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "1bb7b315bcc9820dedc0e243c2cc75b444987bda98bdc58fe85f4bb94bdf58b9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "e313c0ed1451639ddfbf737c01331f701c921de9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "1d25006130fe4305f9e79953eafe5b2d61d9d3b3185c6305d63129378218ebb2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "riscv64"
git-tree-sha1 = "251e0dd2849eb02ba51b19f429b4dc71cae3494e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ec9818ffcc2081521bb5d32d5c4f05448712b71c2b3da9dcb1f8a9f2ce467c2c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.riscv64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "8e10944f03089ea0139814d5b5e75fe23c7d4c96"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "517cba318beeb37593ae1a75ec1153ab3138e95ff44454305fcabe0259099ad9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "a8a50304b330de9f3709e852f8d708ed7f7feb7f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "87fdba085ef3526b699a6b0d0d0d9a7301c55c2ceb5df9e8ebb372510ab2c379"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "bb427dda1dc6afa41aae83444102236dded1a616"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f62dfde61386dfd306699ec877262815f0ddbf3d4bff8fa7881095e3231f1467"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "264e3cd72b690a7bd25ac90f91d32b734f05d5bb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0272c4713aeda8f104ff5473562f7fcce68fde9d69aeaa0458272b06238c5d49"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "264e3cd72b690a7bd25ac90f91d32b734f05d5bb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0272c4713aeda8f104ff5473562f7fcce68fde9d69aeaa0458272b06238c5d49"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "5387612c38e937d3a3aec259a0671794f5d1fd33"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "39f8be385c2f206710ef59eeb3e3f070473f2ab468116bc7f63d15d726139af9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "612d69a172a9026ee92409ae5a9dc351227687cc"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "71ad8f497e66d24db897e34bd3413d089382232cb807b94d8901d636d25b9add"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "dfc7e1777d751fa052802e75f56a76b2c8373b83"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "413723db3d9292a92bcc3637b039cf606fff791f63dab44852b7a92ff089ba24"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "e9ed69bb3b7a67623e9d4787e075cb38a4bacbbc"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "0af067282800cb202165439e9ca748e1c458dbc3e19f4eee5290a60354ccb2e3"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "bcc764503ee7a1175134d29b37e1442ff78283e7"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "02f0a47930ca048928abffcc8b55a4a6606dab9b294ccc54a3c500bdbd43be95"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "a8e764545d1d6f6b95c31b3d3afaaa1147818529"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "bda627c9e7e3fe90227b8c0107fda8621f95705dac4118ebac8c8cb84cc13a03"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.5.4+2/CompilerSupportLibraries.v1.5.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
