[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "a4db66160b453c56175d52a882b74fec9a2be92f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "071a8a0673e1c98f672fcd42b6c64343879a85c0446104bca77bae26788d7b7e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "de9a19f7fbc36d9435264bfc054e3442ad2aab89"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ec3089101d9c2bb9195e395ecbe12960b15860fa4cf4830d09744e9f57b77879"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "0062ef2c9427660e0e61ca81aeb879ccc46884bc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "de65b13dd701285208b0e81543f47ca2bbd829d8e0cceaca7b0c1b7966ab20ef"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "b07de014b80b8c979f5b1c750bd99a2ae0dfbf59"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "b317eab887804e59e7453ce7cb856397601fe273a90a8eddf9f9130bd5b30760"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "079e61df586da8d8fb34f2a4324f4488a73c2c98"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ebb6e52a369cda4687751a860fe6f07f01355633055b10f0816834e7be52df56"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "628e08fd7d7bafe956ab94d79cdaf86df26d246c"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "e8c1faf763e509e26591aa22be9bb824a414df080c8f93f72458f5e0d77bfd51"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "919f8ac741e11c3e2edd8e1f431fbe41d0360ea4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c3b8ec369b744dadce2ab9183ab58d8f566034e2ccaa9285cab39de62aefd38d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "72046ae757383b6b11223851cdb0a33ac2bae21d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d508e1617e94e0c8d2425b4517075f4f7d942155dd1fd5af53fcbba1bb21454b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "8efd0cb317a8000ea92b9a1b7f9f610ba1e81636"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "75b6bd1cfea3dd3827354b0374bbab987889dda86d0c90090b8e57c6daf25cab"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "d8f1df439a696833b83569d51a77e94951053da2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "7897d9825a3d1039120517c55f35c22aa5874d43be684ac04fe2498d6a569e00"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "f6da07c7ad3473aaf4c904160e0637ab90df9cbe"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "6bbcc60e233327c58e9d0a08ec3bd009da7da10957f848ac49f3921093ad71f1"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "749364cf45bc532a4f9d07c66a5b4d5c06a6946e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d64b2a76c1f9bef478ab3d24ea410e41465d65e8c294cd9849eef66a3f650ab3"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "26fa66daff403303aeab6e0b901dc4d6ed8b5b74"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "5748a3e67e79d0de683da98e5fec2526371c73c60541e854da5dba45dd09a455"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "106f04f992de88e7cf0f28a18fcdb72c12da2c72"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a5d7100578770cc855583c8633f9879e112ea79c4ae9bcafdb71934ff680bdde"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "ad5b4e0653c3bfb4415ce98884fcf7bc29b02947"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "518fbfcc332d34930df4f8fa233a5afad101274fd2ea1022ff3ce5ebb6230d2e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "1f6b47aac9ecc6e1cdafd58ade9c730232b67166"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "44322baec17ba50fb50903e8ffa9da6b3111b493c3e4e656435994d66afcd9ac"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "9e45c5c6856496f2bc3baaf631a46abf6d87d1e6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e5f2c35f5e4c63d7569272485c362ac1d3ad1b8144d49631fa6b7d414adb86b8"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "55569f10a8648a9adba888b60a7c787cc861f4c1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f15edabec1ca29616bab51e6aebff6dbd6b4a308b9cbbb81ec4407566008faf6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "f30670d526452e8010c39ead74914cff2156e62d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f26317d0d0accf522b82359d9643a5c169a281d0ef4db7a5b971a584dd8cf175"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "c4854f11d8234357f5eedc77f2b35a36f0b83ace"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "7ddf57799d16a680b4ee12c9efad09c54e8fe8d707bb3e6c6427e197ac7bfb6b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "70a0c926923fba869742676418c661351f307e3d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "dbb1c7413bfbb65f0ce4061bfe2671f19d59573891c7075cf9346bcd725e9592"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "ab265ad8b0f8a44e194a0c604194c5ffc9c8e10a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5352619bb81061301a91069855085ec5a714b3ea0bfd9650890691ff21d032c7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "74a8c441af12a620abcc0462e1c23e11bc3b97b2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "8ef3a29084e8a1c1b5851c69b9c2502647e9d52db1ba06c9e9338f159004a1e7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "0ec08888128563ccf81566c7d6e8a9756eadb0e9"
libgfortran_version = "4.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "e5f222185c55df0425c6d8e65184c8c76440be1bd97945b71346484cce09d3ff"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "8315373306c151d5f3e469029f0472142ec971f2"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "d2be226a1f8f89f255318a7154c330fc5e7a1ab63ccb85ec5fe99aafc2324bd5"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "d612da0e6a3536ca128ca1532debf8cbf2442990"
libgfortran_version = "3.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "7cb7087b81ca726e77c1fd35896de250f365231473cb38c100679ddd966c41a0"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "688d20afddd56089ab845ae48fcac20b06866cff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f453fa222d2a49a1297e342fae0b6041f14798af585d34e241bca480dd3777d8"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "4f4046499655c22b6a04e26b27aa8789980219ef"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "e6c36d407c5ca8f75739c20a5f6ed4e2ee851e489ff44dfbc726f1f3ade393f2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "8765179231003524548cd42badf835c1b34adbb1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "fc2199782a27964daaa3b9329f487991f32f81604d7dd326aed33e8d1c91f99b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "4c521565978de4c6658e4c39ad9db5d5e3c81363"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "e640efcda02bb304aad9c746157f10cd3a8074ff482c0003039dc6e7a3a537f3"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "ad978949eb4896fc592dfecfff57db2a583f5b43"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "6a9dd7c7f3cbbf5a31a4a093f04b391dc5f53c1027e211980c3da9d6b3c5c93a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "f9aa08e85f0dcdd4975bd8a40bfb3ae1e96d9433"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "42158836a3cff3002b2b094560bd00396ca6e5cb83b95d218d184be939896e0b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "bffd75339fa4cf683dbdf60977a8b4aea73d0ead"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ea4648168703681f6b68050a5ca3555d1734c807c4ab127744bd009c75c30a32"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "d638f76a1c910b9f9452655b1d31ef29b8bc7806"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "6496d4552df438f7d1fad9152e579b144458c5b6cae65f6bc165e864c1345810"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "0093affdec1a3d7b0fdf7b43df9ea324db60332e"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "d10f3e99aaabd4272c0279b2fea5afc0afb55626da5be4bf64fe1d2fe0204964"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "5ef236196dc2c91bb2e6eed286ce9c9325678bb5"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "248115068ea16938338450afbd75cb11cee7e7d77fb9f807272ac5ea436626a5"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "ed054529d168d08f4a0725fb7c44b6160e71aca4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "1ad04996ca2a6222921b4c5011bf02c001d012d9349fe624e2eb15ef771fb25a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "529ee29a415e5235cce9c1527846a4f025cf98b1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e031015855b6df3f06875c0dc9bdd4e6f8d4f8c41f5f6caf30e010609d22f97e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "739263893aba2a77d0adc0a4f8675301c8b856cd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b450f26c02cd79cc11cf6e261afcd632be1e3b81de9f92081a47df9d6c3202d7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-musl-libgfortran4.tar.gz"
