[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "90a04f05a74344f99166d0a8051de3e5ebfee553"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "bbb42c1b4a8945673653f1391e1f37cc87c95987f519e55ceafdc653c81e1abe"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "9514823efb720838c85ffbe0aa15b9dfbf914ece"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "67d40ccd0f00b0c703d853f6cb52f3e79275982cbabf0781c306e4942809baaf"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "ac9bb146e1da3dc6769c1058f30b39452ffd9fb0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "2f70b77318bd580df59f5f6bfeb20bcdfda81eaffcdad8a0b70fee9b1dd0bb19"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "0ee59882b68c211601e31203ba057cb827f5c693"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "89a501d4bc62a6c8fe189b0aae958301451166a8430ca4f09c64436426e74981"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "88b1fddb0f781cabb5d50cdbf173cb5157adba1c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "2cce6a70db95661be33e06b7925d504252497e61116fd49196e1bd474880dff9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "47216c8c90b6a06fdca39404424e0babc79daef8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "3a24dce525af11ff2f41e873b1581ef1129e99f14047e1707ac263e82f70562f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "910fbb294c88e6e462640a1585ad15242abf798e"
libgfortran_version = "3.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "5f98e658e518b72881b16be63f041f750770743af984e2f84a485e940c9d7496"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "17c7fa38717029748ad21011262c72b5e0ab7852"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "68242134dac28803b9074d8db60447b35af710843deae3d06c0697dad49b2512"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "6f44be5092a3b91eb1eb15dc33c878f453691b0b"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "8eaf07a909b3d2777e7bec444aec0c1c55a58e4c8f13a362dcc2b3e30631d156"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "228c497e07a0ce48aa0733a3079d0c94517a8d45"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "607e0e22e1cc42b5dc889387777c0ada0f865a4c268b66e3f8aab067e4808c57"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "a4a49f5ad1fe3b43c3c21e7ab5f8be714552de7f"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "9bbbfa8e37ee6ec9ca5442e39922792f91ba4256e5e6910f7efc1501bd963f51"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "b5e0c2ce3ddfcf7f6ad0e8faca7d14ad74622d4f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "6ee0aedca78ae4c4e1e5aa3e1f691df220d4cfea183c68c3dbf189fe37017cea"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "30ea086f8136f723c4b0f09434beaec9e41115be"
libgfortran_version = "4.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "f5b6deb70817ab13b32a1ed35598fc40cf1b162e18ebf51b07da7756b82e98ed"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "d9c96a996aa0822ebee7bce884d94bf807773256"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "85ee93896a3d2e7427f981fb141dbfc87c77ec35c8b8b0fdeb13721ddffe0258"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "f4041584717c934e3b2f3f215eb95cc5247f851d"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "a64ba072892c92bb037c69610ffe3cc8c5a49c45b6f8dc9cefca18902849f0cd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "66aeb912dab301b18ba0b4dd2439c8b3b38e295e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "49aaf5f6793cd9edcb639e72de550950e07762cc66938f087b704b6428f257f5"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "cb7c9b4225991261fc63754e9e4e4eb78e2cb7b5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "86a912c6ea3d306ae0d5f718c7b1e389f255e749fac0dc407fff00c7d4804201"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "64714852e95e99afbe0afbb17abab34c32b44c7e"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "e723910c5cd18bdd53a43afe83f47b09295e8771a42aac5952e7577da71e3edf"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+1/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "aaa7f60842737ef6e97918bc507005eb127e10c1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0bc06cf4be5fcdad30a15bf2a128c0cc33dc6251e7eec1e4dbc9bd8ac75f97ff"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.i686-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "7b9f51792b90ba7dac7e4b281eeb7168de3bb868"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "13e7cd5e6c072ba9e5616b1abffd669db46ad6c049e05101605a949e1cd9c468"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.i686-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "ca618b4b177878deb0f1727ffdf51a893d38c7f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "528f3fae07e0ec6efd85d15b2ea7065dcc5b5ab60db5961fd53ab35d3c988437"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "2449504d22e162105c88a821b216ccd999f3526a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "87b10c3485bb839a4fa8a73dae188ea8b0f3a5032e03a06578af1e8c4bdf9c8c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "754f86a26c602d247791127d222fb5b851d6fa27"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "8477b96f814b89f0ba3d152287b3a055032ea7f55b1a38082f158cf3e7007da6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "17246ced06ea24c46b8add2be9fbab3987bd242c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "9e51e7b1c95e7fbc83fe6bfe4c8cb0b3629e81761469cc805a3952b3c6ecd832"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "0b4a7692cb786aa4a7aaf190aaaa6dff52c9d38f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ffb19f040795da481db3fb96bdb960eee68c0c5f1f4bc59a1f10c3ef49d98745"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "5865c979f67ab9fc503368c8eb89b85afaac82f6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ffe216b22c484741e6773fdb572d8b801b8f8e67bf3182df4cadbe7d43335c9b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "addf752411c52e1332b58d5726856222a4a94ff6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "7a0a45917530bd8d2dac99b0a955e5561ea585e577d07862b5faedae7a0d1299"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "474c7d3a11e5c53cbcbb659c8b5005ec12856718"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "58a1f364bd72ee4d412c3efc2519d72946e7a52f46c7ef150a147ef69fed1d60"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "55e58525ca6085459ca1ba6af59eac01e5ad7c92"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "aa188deb8d8931f92d2be6a5b6e2f14401a27b146c1357693f215d3e67df507f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "8cbfa671b664cbf6a341cd977c7531bddcbc99b0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "32986ff9c19eeae3e4a873e4071782dcece9292876d9c4624b5aad9ace934eb0"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "3f59f93519edff2d6dc1d6547c303b2785f98991"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b84cb2a71bb4c14a49d07fc7598be327eef338f41b9adf4f95237dfdf144f174"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "d4d8928b9fa920d6f772f90bbf4893b7283a8561"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "2f3d9ed43c531ebd2df7d3b106c608fda14324f763db53d91c8b1cb9cbb86a6c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "1b075dfc5ff1957a19a19b0dceb40b78207a9092"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d2c4c9f5e71cc25d5d0304ec08bb89e90c32542b5f134436f125cfed5c6ff4b4"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "12b1cf54ed27b602e0d25a4f08c9df7c214b3ee2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d53bcf53f3daea21a29de4a944bedf779f94e8b16408aa069f178e4a1a31dcd5"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.i686-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "39c59a347a8eca585aba0351fe4415093b8ba15c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5f418fcbc5c6689f5d57b9daf59a0d03e6e0ad3beaadee13b4b3e9549454cacd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.i686-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "c7dc84f47c6fcef4481a1c213116abf83d9263f1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "73d6ceaaf60835c08d4ce1ba40bc72298923d24c981bc1f230682ad5439a4ff4"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "c8726e3aa0105eb6be755ea78bc444abcbaa9e04"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4a4c4c8f5b22332d5aa5aa562efccb290e20ec2105da84b9acadb5ac96448349"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "b61a2e8605d5ce8f4fdb3a6cf1db8d117aa45193"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a819456da1af3151a570fbb91f63c8ff20fedf7849ded6ff5421232c9af36af8"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "b3e13ee7598429048ae6dd0ec1397293d4b6145f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4f6347acb98d3767b4ae98b4c1fb7304cb6fd9c264972e72c24cd7af70371eeb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.2+0/CompilerSupportLibraries.v0.2.2.x86_64-linux-musl-libgfortran5.tar.gz"
