[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "30fb46e7226cf835fa8193c7d4a45c140e1cd94e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "9bb93bc53d054b1115b4ed5d127c3c6e3bf6d1dbf5ea82df680b333915fde420"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "cec1a9dd637a2f780cd58cff0e30bc541c7b5d92"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "655b2749b8a996001745c3700e568657724db857f4dcd68ba30145fc7d3c5c8e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "35ab2a848f3a18f19535ab7c811bdb8fd9d820ca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f969b04d81614c51cea1015c80325fafea9d3dac02c8d42e550495c4744680fd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bbf38c088dc3ca174bc60b0be1e505b1e0393f6c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "04f0cbf96a06e3a771408d600e6b433644ab41374dbc49e7b9b3acba5b2da07a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bbf38c088dc3ca174bc60b0be1e505b1e0393f6c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "04f0cbf96a06e3a771408d600e6b433644ab41374dbc49e7b9b3acba5b2da07a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "6b10c6fdf1d0ced43256baa17f37d50eb0911003"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "cbb351549d26850b08c3eb0a2e3905140531ea35d0f51bb40d79f7b0f68cb201"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "riscv64"
git-tree-sha1 = "3d729ef19bc68dab58bd5982ecf85f9e95f7023e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "87671bd15122a61465039d6029d39f6df2b6ff79086dc85bfd8cc70566844cbf"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.riscv64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "b75bbad8e97a8e18be661e5bf621294cee8aaa00"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "cc85d65030ee488ba5fbd0c7d7227363d7f1edadb53ce183b1fc62f0d1d1765b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "a65db16707161fe98605657b0a7eb5d83204f2d0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ea8bae3afe9522a52016779cce00d699e5e823d6794aa106509c0ea0c97e1b92"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "1ad737c4e03c6bee2fcb2de5e20f400e4c51c080"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "43edf0f18b7a4cb6ecfad9060732ab193a0c0c75fad81dd37df49a4c725c5798"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "287b35be9eb7405737ab31de47949189a31d46fa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e0e8733d855fbbebeb7063a7144ae08d1a10bdd3dc7aeb1a34ef6495e5dc0aef"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "287b35be9eb7405737ab31de47949189a31d46fa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e0e8733d855fbbebeb7063a7144ae08d1a10bdd3dc7aeb1a34ef6495e5dc0aef"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "d837801dd96a1fba305a19ac446c76f2064ba382"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "28a051cb0dd331ea758c4e33e6271b7fa022015707f5dae9398c68ac4765fef5"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "f9547d56705c03a6e887a01aeb0f0b6b030b7060"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "c7d0330a55d3b32fbe1b6f73c43e9b9d6649f23b6d9034efd5e107b1d537ab53"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "037e25233d60903d442555a1fd787756027c88f7"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "30eb8be3a6d7e45f6f72cd2802f1476765bf0531a33af1e453263bc3e2787ef7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "4c575ef27f1f7a520a963cd8e9ac50cccb373bfe"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "46cabf32a9450d4cd5f21123edb8c91eadcd2992a1b3b2a0ba781bec8082b967"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "49cf2fc8596f30113a4a53108bc1c4dd37221ab1"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "6b1e72e228d3cab8d19b194f9e27c9bdf521c52bd466eab2f1f52aa19f1659d1"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "28660ba054d7f95eba9f055871296133d9c298a8"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "e1faf438e9712f4c70f0b8b93083ff110dc9b47f2fa6342787fe9ab4764a30f2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.1.2+0/CompilerSupportLibraries.v1.1.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
