[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "6a7f4d8d9a2a592dc2ee2594daf705968a377fd6"
libgfortran_version = "4.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "c33b49fb91a4d7c9f49f7e4ee5e5f74eeaadc2521ee19cf48e36aa424bf8c1d2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "e66b643903c3e740c9a07b6ac4bdcfd13a22219b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "7184e5db9b0a7ffc44ffac477b098471458c22cf26f308045b4f6155852fa3e3"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "8493b14001ef38183b1263982bd2a3c011b3dec9"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "68e4b75e695a2623ec3f27bdc83edbd77f8c7eea1834e2f3ec622d7dcef24460"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "1656c2ab2cf30e3793225b1dce50218b199c1dcd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c06b14bef16d0e589587962d2b66646e9bb69ed27dbba9d084ace30dcdba9501"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "35466bf27617c7b72a9ea42652cba715b0be1287"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ac6e05e92e39f6a79896a9b5abd086ad10ee3040c78887ff6dbbdfc9236ea3ed"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "ee263b693e8b3c519972e9c49e2ade8cff967d19"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ff0d4bbfe5806122d8a1b37d70fb7487eb3e970ae44b744d21c5800aa8b2b27a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "4b5ea3370c088cf3232671de3de85b7608abaee0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4d29a0422b22291092cda54b79e42fbb433d30e29417daa0f625b7d1bde8f743"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "2b6eddf7c1f281662258111e2e0b12704d2c810e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b3182416efdc121b9e531f7b476ac2382b4be65004fc6766d1e4410c72083063"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "7a6ff205f5ce9946ce97f33950e865249f596046"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "e853935051933eca9442750adf0dd754b2bf315139b355ca3161aba01dcc9773"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "fe9ffd0167a0f15293d1c9e3e22ab405b9798647"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a5fc32844babe9cf31f9bbef574933b3a6bb28ff767212cb2dcb8efe3b482875"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "0b4c6a1455ac663cb82979c0fe32004a4913a9be"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "4e102d274cf4a661368428ae91896d270954c2a579a1a16d7c55b627314701cd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "f96d414bd88448f37efaf9310744d108fe60b649"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "58f855c1f75d9ca029bd1333dcb2b0417ec66724b3cdabbc8e2f4c98a7f3ad71"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "916c12898eeb8acb7d7e1e6dc9f874d3dd48f681"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5c6ae731592cfddded5b30ba02d6a9afe55e319477a220831363d55fc3651473"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "d3f3dab3545c7ddb4ea00954905fd3cb4cb2d04c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "cbca7ba39e56c9255a61a2f0e66a0da457c5458115e5ba396a2c27503e466f3c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "ff3b038db9efe615405ecd646106c064ba607f39"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "abe73cdd1a56418ba74fc58f3f4b434769c0489d13e3a6efdb1518c02761c57c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "36f0143a0666e92c6501651d26d8e4f309a145a5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "40f64d087f943ff15f84386e90be2e9716119242c59592bd42b128f45900c874"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "de462abd765338f3d80ad8130ae02e406471ba71"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "aa6c22baaa0b54d164b35f837e0fe5e1fb7626c21d8186df350a306d6b52f8c4"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "c4c0af96151e5daf715fb6af7929c0b79d515a9e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "eadc01af13327f1d6def7ffa701732b8a2f7bc54b9b4742203c815b608a2cabf"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "6f622a38082b99d01e47ccae8c33b2bf0c4c60ba"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0b6e0a34c8adf3af5ab10d6aa27be6dff6f62b6c2f6456b709a93d1c30d40416"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "17098ee228b0a673c0333c9dcfd2f61ca2ca1833"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "92918708535e10cd4407dcbb3de406e444a6a0489ff7f534fcff31f25116e101"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "6a953bdab1e37d97535cf7c8c03df6e71ef99459"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "78b1a76b4779d79393cc407d2a37ae9a7d53dd69dcf1293642aa92253a51da2e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "9420494a0b4bb27cad51065eed5b1d040ddbdd3c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "20bdcd6e9617cc4d48e96abb4dc4d9c36c9f6ffeb72e2e2b303c79193a5c5143"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "4121c612c88387e00fe0fdb26bc742e8b0e94d2d"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "f254a811847dd955f75ff4ed0294227e94c6ef2b7a70bd24bb85e8aaeec3020e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "a927d4e776cde321fe775632151030c2572b9ee1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a8315268fdff3b1544f7db615b1384c2e6e1c525c56ca101e400a7108afed84e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "06975be76da9c7df6c8961800b39534c59efefae"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "60f547e1156996364154d25f78606b1ba15b56336e28e33d7bab145097c38edc"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "bf56ea0c7049c25dc45edfb0bc58a4c43514d446"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "37981de97a662e88b1ea8b4d8c67b2dce0b48934dcad2ec92af7885f0d296e1a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "86d67edcdadf5f298b9ffc68e013b6c91a5032a2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b306976e1d3f0bfd4a82ac0d5682629eadcb1c6bfe4cc3c8e031babfd4df52e0"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "d3f15ed873df5e411a516f07280f2f7cd173d261"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "7d761284ba9db46bdf49779f175089950d074ce04dc4e72cc5ea5334a922d4b1"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "014770bc56e76aab34d9dc5673a0eb23e82974db"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a95ae3a986040433d852df60126ee1d7057c1cf6505a0c95f39f3f865be75873"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "ac7a46020581080c3e7a1b47a44d6301accbeaab"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "037e081f7878e2c330c88fc2315e5904e8122368425a583ce4664088c0be21fe"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "3d5c6314d26aa563b9eb00181ab8ea6dfc086064"
libgfortran_version = "3.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "8abc966c13e30b9b6e64a73713ee643f60241664cbbc7e814f25551b37134738"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "127607195e230d9783e768dcd189404a2c859b5b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "8639ce19a342a68579bd6336b7e607619b638aed6a58321f671f10f174276c9e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "8679fca6162bf3c38ba9373bd7583acad2cf3595"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "b24552a93b70eb35a2703c038cfcaf6c0b5c9a33f116ee65e22e105f87470c64"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "59276e1ebdc1b6d0d6c217cc23ae749c31ac4bfd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f899dade6ffc303e92a955db7566da29342558200a8ae2c739ebc53198c44aca"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "9c7d8ec3c1367758a9897bbe87f01972becaf343"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "80b84930a4553d7c38609663f061595a755ce0d00c85c23f29cfe754e61ab036"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "021ed1c64218071b348b689d1291e798d1946010"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "fa2e5d7443613ac4fe863ddb637e446d6e6a6ddf688d87992744ce7ef85a65c0"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "fcfc613205272e55f630850132f22dd534ce735d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "618a45140fea3b7df430cedc651c510720ead4fac958773d13b1880208257f8b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.i686-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "98e103ee8f900de34e3a326341e303128ae94859"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "77e20dd6cc09a4fa63d12c7f51836c84815b26b95fcc51e94c6828b98d7751c9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "1bb66b2b4ebb8ab250d875e9644b1fbc9e8d7887"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "ec6103aee3ee1d5afd5b1736b7c81e9e23cc38445fdaf1a9a847e9a2d4d849b4"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.1+0/CompilerSupportLibraries.v0.3.1.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
