[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "c5005417f853417170eadf35cb73e436ef2aad48"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "beb80d6faf08951c7041cf502726e7c046c47c0a68d5a8abc21ce2353f4ab5a2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "55551beae8714a08397caf745ebd93371658ddfe"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "dd86fae177bf6015bb3d743e5268a2b19a597fd15ce3e95d00b603c5301fc579"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "dc0f3b27d71da70b82270b06dff907e816ba1c13"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "581f1a71cf351ba4c10f40cd7a4929c68a3db884f0b8b151282b5ec5b7f3e628"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "6bfdba54df5e0ee82f12989053655635a798670c"
libgfortran_version = "4.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "4c59a344094fd96b745149d74a1ede1a7388a8fa84aca7e0feeb88b631d30e78"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "dfeece0f29b820474907aac64a5a5ccb800e3625"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "da3135b85f2517e3c598b918382e78350a4fbe291eb02637f74432deae084426"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "c981b9d479ff033a7af21240be712003437015b9"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "c397883220b83e69cf17d2763469d9927406e74ea2399ca7813f0fd442c509ee"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "837f8be083b3fd2c439c0482cb75a1a1c6a31874"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "2752d4236df6c95b8e487daf463b0cc0f328326b14e3a961f61f3f307c022d93"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "dc4491b1ae0d75ec540b32c3b26d9f65937d8e74"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "34e38b5e7fc72da47f8860b6901e915372cec02f463302d4defa4a6fb31d0a33"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "e7690e7d0cac7c583e3e2a6cd49bf264c78f9f8b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d7f60bd706af8ec63bc9aebdcc61537f12c0af07f95ac6c3c27b0c658b38eb32"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "2490e9bef75ea7a55b1e6ee089297af5a07da8d8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "6b832be4ec66f7b7809e32321d0fc338fbd1b68c271b35fef7557990a3777466"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "27824432e9c54cfe9e72884fbf43b86fd0c25548"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "7bb24ebf9a96ef89ee4a03a37bc3e7135ebc4180b7a8d492c8b6f8decabbfa72"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "89137f644e61bb2e9619704445193c9a884d1c49"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5d62d91c4bce1a47f91613fd1e2c7b08dff69b4dc91b5d13d7a2f7ec3070e612"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "b26490716b703e3fffe6fd8343d2cf65108ef19b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "1687cffe461e8d107f9cfae80aa1534f9eee120675b709d3e6237be9fa254a5f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "2272d9eb62bb5a1056934bf85ccf19f3edb2c075"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f18fd689aba3bc382038ca2ed455ec551e6dd4b2165ea09f7dea252c1dcc7072"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "ad39ad1b610a7a875f8c9763487b5a41cae492d4"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "9090ec194ddb6249231d1b8eb47f11d803c3de1307f7002e4df583d45b61c7a2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "2f9fb6bea78982ac6f2f0ab3e9de543e948661fb"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "8f45e9b024334df7ab560f856164e8cfb10161a55c59eb6ef353f8c01b123c29"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "66cf26c635db866e28786fd3c2d0fa6316e5a3ce"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "320923e7154b317238a0bfe42a58f4708a66b1ca48d1469289621f1ce3cee7a6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "704b4534872b8603551ad8f214af80094ebc9cdd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "11414ee7cf229c8162f43f1e01abd73a73fc761975aec7866dabbeb298f1d115"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "f9176e0b7a49c6c3bfd54829cbe2e39966318566"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e3fe97f82844ec487b89853d381522d98834789543bcb0a15ba703f622dd24fd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "aff74bbf0a0449767da395807188e80c1ce9992b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c97fbfef6e8202106aa679cfc4523ff32421500e62d28728835d2ddce837e72d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "8f616df348e2202b1b5240887f7df229059c58f0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "773d8c939359bcc12aca0dd456811fefff95ed4e53d0c9f08ba94d9c7fbfb26f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "c5ba2e5de625e7a518b194527ca32bdea1124ef5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0698f2a71752286ee315387faa204c8e9855a229f2cbdf97a56da0b1f1bbc254"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "93c265bf07d728b6eb4a9b50293f0409a5c79cdb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "6ce3a30fe525037fb5ac343331db5ac7d1fdb1fc489a3e5d07a59ce3e9fa44eb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "75be1a61e44ed44f20751fa213b1f7f05363e675"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "62c7515d3276050f73c8105cb3eef7a228e5411bcc3ae5d6f6bd3647309990bd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "f35d9ada8d0f05f031888cc606256f24498d870d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "97b4c2192cc4d9101ed9d40a270931668db8fff521d1d3107a4c6cdca91455d6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "293ea961dcde4e88f0f4cd2b086a59d1f0e8962e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "75c177abfa212e4e19a04332e1ffccc35f05567a9530cf1b14c3b5c8f72e988f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "d72db22462ea5f2d4c91128b045180efdec743b7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4c9612b21ba4c786be042dcdce4cd9b46275e17db5a861cc2a1f1c86b27f7e91"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "a3771310523c69d17812e3920f3d4ead4510ea87"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "91a08e0cf423f8e7530b33dcb4cea848a8c8cf8ee663ae3faf7aba9e92fc8793"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "01ddf9567cced247c49ad4569e2eb44ef97a1eb4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "bbb44723c25769c2f83c3c07c69d323293ad7be5ed1f9060acbeab46e9ad7f81"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "16b96e998eedf0a9336b6590d1c7f68efd0cb699"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5ddd59ac746b3d12ba84917e37f9b825209bb6d4db8c358a3563f68eb33493b6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "90edfc3b9717711f210dd9c7682cd78ff0d971d2"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "99ab2abc27b8bd510178943f5849e45d63f67bbe218132162e474550febfefcf"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "5fd0557b61fa09509df26752f00eb81b77e98fd3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "426d78cf2d0c02d30b7d59481e1fc1f80f83b3d688b6b334e4925c21d1a6b6fd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "9badc6c4a2f3efb786dea2d22ce4c57dbc6e6086"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "6eda15b981dcac5668347853f927ebc448dd5dad3fd14ae09c39702408c7f52f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "78d109131469d5fabab697cd64dbeaa654f543b9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "acd9354d2e615618dc9746ab80042e0e962b99500ac147cb35571b90911b25c6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "390485c342f7b77a8448cd0d81e945d7aa0d95f7"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "ae7ac53dcb338ca952c5ce6b99a9eefa87a7203ee10b94625de04d348d69256e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "189f04033e3df7895c02b25b2ed62ff1e0878f11"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "93d5e5a93a81a8bb97fc9324f40c2de0fabe62fd0674c5a233b8e7b9949cd395"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "5179dbc914e6eee45d6f4b45fcb9ff9a166518b9"
libgfortran_version = "3.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "2cd90d7067e4d7bf507d44e2658c80f5be1231d36acf9ada83c9c991de9b493e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "708b7a32e0eee60901a5e8bfb910093e629576cf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4e0af751c00a1dd59c79391aed717347b888573b9419fcb7fee3eca9211003b5"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "bd259781f9247790f6e686a13aae5de3868a961c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "91b865979be25e4da618eb342b6773a2e1e361c4524656da02bd7302c0240bf7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
