[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "f30e59bcfe607e0e41ab995d3f68d4cb2db44c05"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "516b2024f2c35a7c639615d038d207089c87136400cf4ea66f297445e922d029"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "89dc9d4837308f8e0ab5bd0d5f75ea0c5121ef18"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b0edf4d6193f72da0b4372f77b5b730ccf7e6bd82b0d602e41b510921a9a5649"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "d491e22fa46a95a6c71b3f2212835d35f13d944a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0ad0e3bcfac9066d4c88375837c0f22b69244161911cd18d102c4f9609649dc9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "83e5bafbb81aea973bb785a3399a165b1c87e92d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "66130a4b42b5d9de441f5620881718dc21869162465b6f2e07311b82b99c0fa7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83e5bafbb81aea973bb785a3399a165b1c87e92d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "66130a4b42b5d9de441f5620881718dc21869162465b6f2e07311b82b99c0fa7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "0bee9526d44956f47e544101190877ff118d8270"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "8a4ccd86e70f872cb19096d60981f0b0ff7cc28b6e2fc3dd0b90c409bcda52ae"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "riscv64"
git-tree-sha1 = "b0c597193f633e3dd9c2cbf0e3b343e954ec4555"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a19d238b39cae0bf6ea7dc6b0dd5df4e3a5b0615b9522428bfb383cc1cd86649"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "795cdd3e6c6fb8a945247a61f36517bb2d74210c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "9f4732215ba1be44e24229cb991c517db9dfb352a3fdece706bb65552fce0872"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "88a54f2a333ceb93decf919c76c75b564c40e99f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c2d7122db7a986bcadbae9c44c0950a90379b4fe45fe25a8a59009237212678f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "ce5b4a5049d5b52d193e813bf876e002e9cfd5c5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "07aeef2650596154005a8603d72ce29c5deb5db065f4365c27262bf577af056c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ac2948ba726d1e289ed8809eda7850aea6d3b8bc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c3666e6ad27d1499a96530ffafeb4b566f3f4d659a24b1e84a8a0ab7d7bfeb22"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac2948ba726d1e289ed8809eda7850aea6d3b8bc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c3666e6ad27d1499a96530ffafeb4b566f3f4d659a24b1e84a8a0ab7d7bfeb22"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "6df3ed27700d20ec59efa45dbe7ef4cffd5423ac"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "df9e484fa813ad8e1ba103470831c86a2d15f3723eecf29d900fffc6c79ef6b2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "f9547d56705c03a6e887a01aeb0f0b6b030b7060"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "c7d0330a55d3b32fbe1b6f73c43e9b9d6649f23b6d9034efd5e107b1d537ab53"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "fdf79f4a6451d9d65e0c111a042e342e50e90456"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "2a911a1dd08f3c96f4cf88ee7aa42929da81233191878ececdeeb5e4de6baa5c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "10042451f875bf57428810c4940782936e1c4b08"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "33cb678b7a1198aa6cf0aa6ba4e42fca72a8372851750000dc1e1b3dc0ea630d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "374472ed3a2641ffb7d9cc5977a18bd2830ac5cd"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "3dbfd4b3470339afaa69708240b25c8a8d3d2534eca1be5307eb9ca1b614f831"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "f337b3831f25ce97097f5bb30931c3414bdc116a"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "aac06290d5cb9c6094d066a61096a94e690ed5e6bf32006dccce69baf0c9dbea"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v1.4.0+1/CompilerSupportLibraries.v1.4.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
