[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "4de500b965f7ff41e262b3164fcfae74e8a4e3d8"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "030831e82d725c82297e0373e9473989a39f18d995edd0d49bda1244de488e0f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "0e1e5cdaa1cf5f9a7fd1e1e40a54cb5f1f2b9039"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "dfee8271f4c34525042d38e764ab2d82b25506da26561e2a5c0f72adb8eb88a4"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "a73cb5c5685e911561c0de2f964595a178ae4d9a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "69e9db882b46a7dc935425f54eba1050768c390b21784539c588c19f0d7cecd6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "ed9f904efb8b741d062a93c6b0230e26a148fe0b"
libgfortran_version = "4.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "7adf315604f9112259b6febbbd4f6a1e2fff5945ca47b8d4944210dbab786c65"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "82b5559cba095583bdebbb5354858d56c298d25d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d0a8b63cbc691d4e717122308c396995e5df81880eb5fce28e7d2b6c886adb1e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "0ddace6d218f7b939fd686fd412bde36dbade546"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "631b12c7c2e6d26059fca8672505cfb433fe2038048ad633852050738f13e831"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "829792d5c44050cd440f8862c7cc1e08b9e6d38e"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "6b7c309e6aef856ba31f2d4adaf7e6a505030b65ba755338dc0eedec5378c552"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "9968943f02c0f7c9dc92d1669e8bfae7b832aec9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "fdefe2438f26e19e4c595c034015878f58529920bef441bab408e97f49d82208"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "a795fde9e0ba333a9a3d6509e414e2beb85b2600"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "188c2edfe7ec89f8a78efdea7c6dcc467a58f63d94ac22d2cb7d22d5adaaa239"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "af0077fb3df12c1d1c0bf78c18a320be14413033"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "61066be7e685d551f2120dff19ad6438c08172b92c66f50e0ef6e71572d49e15"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "1d0b14069a61ccffc876e6a3279731e40fba07c8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a9cc85a0bd53384e84c3203961c4592cb5d8a2a759be9ff122d3bfb7a2869e51"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "413fdcfc984fc5eb5a283080a3115e5564af29dc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "19ff75a25fe10631effead8cc58bf63c98d1b241ea48288f1035b1229f53230c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "44342b356c74d76d660574e4488d8d60bb9fb687"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "2f400e1fba358d579be05e1bd0e6a806abd2c62056ac09785142f846cfc44254"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "9b6946ed964e1ba8f52c2a46188756538ba65995"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "518e2dc58d668900700af05968364f19db9aacaa0185a4d3e06f28e4a347e271"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "aba6f7de515e170ba9fed74fddfe16a9f1d04691"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "b66ab1a20a93c0a0e33a48ae17fd485bcac08cb28a0d8f15d4352f3a3e8f04e2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "6a7d7174da1d4af066e3b87a7438fea3af02f7a6"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "cf419c4d8de63ecc5981b0b5c503e86c7131a15bb3cf7ef1f67c9074ef0228c8"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "f9ae999f2d9f250a34820cf0b2c781e4f068b6a8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "fb64e32a4b3b24c44bd08bc5f675e518068c0851d503dc7779b10a337760b829"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "9d02dc04d602f1622d85a9f529e503bbef5e1234"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5c782aeacf06bd686c332333095e53f885df74de6f1cf47110346b8d92838f02"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "53bd63550c764322b1d39488db39ab9462ba1230"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "eda57e7d23cc15b37b5f4a551d55e58e471c78f7c6ce78893c5b0e5ea8ed66a8"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "2d0194ca02dce9b24ce1d32935ffbcc2880cc072"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b0ae890255120679091a0f341c3d10194e4b8405e445818eddfff50867103d5d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "e156392017ad3d47c4d03c623f37c93b25edfd32"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "7758bad5f8d676309d204a0029d211f9f78748beca45d7ecaf458b1f73ea5943"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "b5c5d001f027e5f0fe10291808b737eb4bfa18bd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ccaf1b17008eefb661541278b0171d241c625ba8d38e3609ad921ebaa2996d4b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "3cc8bb458fb5fff48b2d9dc69a810a6da1321181"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "24d21951e99b11ab4074e34f27a6b64d7c781f59bcfde24c43e6d3c60e400c54"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "9ae9942585ad8794bbab2a7bad3c718c46750609"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "5d11542b5e52632344af7bdd1a759aacd8f1781269f9cf6baaabf08dffafafcb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "035a2617ac58407e7a486f1d775c55c599703bdf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "801bf0357aae0e7c22e1737911954770e4d229a1677a82c974ea8ac8406ccc60"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "78c23eb90e8e575ab09da7389516cad472ef412f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ee5b3bb2dc08c101bd3ec1bc38c3af23966f8aa4ebd32fb0fd0ea3b891713cbd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "b3d62abf77b03bd965e9172ecde2b7afec28f6f5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d1463e0c5e1f225cf779f2e42b20ae2813a16f8099f7715e04fa2f17c93f3b44"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "1af8f8036c57cd467a0c11c7ab166f6a9631ab76"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "729d58854579f37b2d7618c95623f6aff949e946f3859a620d9e6499f290919d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "464c08888ed66ddefa23c3407960ffb529354f94"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e6ad21482a7af36c5022699ebeccdc6f2810f59bb3721a70eaa63a19ba32b96b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "896ce9b8c7e46e4f0a79d03dfccde37d4ceddd7b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "790aa0573a16498b01132e80387f921df2bd06b7e41bb0d23ae211d9c3f1992f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "320f9c525ce7d20ee5338f9daaa592b5ce20421f"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "619775ce8fdda468aefbc4076cd6e65f7fdfc68dc55a66dcf5d30cd4312a314a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "79031fa3f4b028e112a42e4922cf769964939b8d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a7ad30ad86475dd4852b147fe3c298faff5235777732d8199cee4b5cf9fbc524"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "dabcce125d0e34c594e723cafcb657f87c15f1f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4389896a16c79ef78cac4de9566f109640d431615890044345c7744248a867b8"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "9abffee143e812c77f7b29c15c1a0fa5fb99f2d7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e591dd8d84623deec79904cb0e543374ec27a60675da937934479b15717a0e28"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.arm-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "736a18f06aedb3a3d9e13fc0caabbfa0a1bd649d"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "0674d5771a3771b3163a2511bfe03c3047533b117101a30dff7bbffb05e1e041"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "fdc567b74c264a02f03ac93b813893318dda3e56"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4a20a7690c585e8c401f2c4c1ef0871eacb165dbcb8f95aa3637e013f2b1c324"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "0ce89581739e9f412355e28e3641b403bd8b3fa1"
libgfortran_version = "3.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "f8aea82a9561b88edc313ce571fe1dca2d9cca18418d32f7cc04791b878a3e81"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "88fa390d407eeaaf2769d0da23c2207861c94793"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d3a2eb8e88bcf8483649105ebb74aad709d158b7328346a5903fccab07f17e54"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.i686-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "20a997b8a283ea975d9c33790eab37a194aaf518"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "07ccb93c2a20edc983f1886a7726b5a5357e1e61a78365f7576d540cc0cf6f39"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.2.0+0/CompilerSupportLibraries.v0.2.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
