[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "e48363ac90b87b1090f1a0e141d895551bade704"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a4612b653d56ddba5f2fe0a2c0d6f3b116aeba54715663971918b448cf4f88dd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "7b22333c1b3603580ff072070ec647a14ccc202c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "44c861f1b91081d6ae9b3ca72d247edb68799d405752e5c5d42cf41e8d399006"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "641eb6873cf135fc8cd67fb708fe7b83782d4142"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "f53de60010826872503d6cf4ebecbf73dfffe594a98e0f705438538e2e059aef"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "28bf316948e6761d49880048741d1c17e9fdab4c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b56ce3e037ce7bd61ef9e7a439a97abfe83a7ac2b7a56db8965409911883c82a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "5d214e53340beaa070e752b87f1821f883924ffd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c23e5da035dd60c02f28284c68b456c0dae106d4bfc4c91db3c7c37e0c7430d3"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "d0fab681d21b44056c235b6b21479400a88e756a"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "f88eb842c2aa25f88c1c8f7786e20347c6e73b1b659b4adad4a8d503af35eb3c"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "0b0acacea4eec5f5318a5e8639eec7341769965c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d8f9a21ce13247d98e20f63f080d01949af493bc8017ad410126b5a6dc5443b0"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "3ebfd1df6f8d635c5ab97ebbe290adf56dfd3a82"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "44f21c4dbd50fc2dcc43cb80011febdf577eba0b2657f1ea41dc05eff422e2cb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.arm-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "3058b8afcac48e014dcf0e10675143a6dcd03de7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "cf9f895f7fdedd7c7a74f7409c980b14c2f961b2d9a4e864f9799b373a68deeb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.arm-linux-musleabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "ef5442c873d491ef5d9ffa47463b020ca78f5210"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "040d9bb1c641d4b749e0c44459ba045d5ecc64386c20f85b2beae394a0fc1de3"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "bebbca424819179908eff846fedf123f3293ec8f"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "93b521a7d937405463579b4ac16b65a23508b88b8c8219af73aa3fd4053f66d8"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "9a9b523ae61655b8da179b713f88154fcaef72cc"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "3b84a29cd9f0d39090d3dba395b42c9537c87a9f340db2837f978b4ee81ab413"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "01b22ed01e3aa1619b6747064f7a1b17abf94584"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0d5e3221a37983f2437d8639f85751ab0eaa7b9cebbe528e030988b25cab56b6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "12e5a8bbf5d82e6e7e4b96983372b535938350de"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ffff3513575c001ebf0b6a9484a2720a1d6374ba92388184eb92b80b7fce0cb1"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "2143dfd0a275e0fd363119cd912ed212317636fa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b0773a21f481938f4ad128cf2b1730d3657131bee559edf3e0659c378b54397a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "05f73aadaabc0b20bad06be0dd7f61728938d36c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5c0c1649ff2e03b0edf48b8de06d674a442ec726afcd0fab5d1b198c46385df7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "d8ffd8dd3a5ad1c61dbcd1bcd3697d0e3f4e054a"
libgfortran_version = "3.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "ef07105285c71be2a685f7667e731c1ffde5fd4222736847b9c49dc73b9da41d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "774f0fabdc75c721b82a243895fe5b7a9cb33b07"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4c0aad4469331ec68c8b29616a9a5322de888a9687e13a47123a0db411569fdd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "6fbd3ac73bbeded74ded2f083945c30560b72abc"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "3329f6f65d54d7110687fe5f6c6d3e465e186fad77607a8c1a2d1f4623f037d7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "7c8248550809d59e64eb7a69d4cb8359519c4507"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "504e9ab99d873d0518432cf73fc0e4481d0d5b53d226b96114cf99dd287337b2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "24f2175e146a93018b070ad4a9dd27c8ba252a60"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a908bd020e4c104f2c7e8f94feb3d97e0b8822d5ed40d74b186a405ce1a8d131"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "260a115f9f42973383f26a5527f90a4c4873fc16"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "0a0baf0bb38d295544e994229c72b6892e7e714ab2df3ff0a00bd796fccc86fb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "584495881cdd63a702761bc5c1ba2656c965db14"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "66df82025c06e0843141d4e5ead3c1745c4f926c6c61cd46628b2ee176c9f961"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "3fdae6ef6112481dcf37842e64c430b2ae2ca7dc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "6160d4fdd47efdb749f2b8f4a13377ceae7961238ebb0df11b02d9a6cd773399"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "c914c373350ee774a299238263c4a07f9ec3f1c1"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "bc28d8798231ee910736a56b48ad4b4d8dee51e02b26b65bc8c79bfe63ce7677"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "e4cc8919920183af3bc41bbea596f67250caf481"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "645c9aeac582237c625536c4b5503e6075b8146a6b0895255bd6eaf3a3178def"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "c48bf1a6bcc781ecd29bf3a7855b07d880abf4e0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "fdfc653ab1b7fc5991c4fc55c9b5dd930bdaa187db7f7bfa25dfe38fdcf4f111"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "510ff44d216054f37fd4e587c3bbfe37acf990d0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "929a5757311b91ea8b99eb7aee6eebb51c32210b0b4579083ef8e0caca75210d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.arm-linux-musleabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "d633272f9c731494aad76ab3f0ae92b0476c02ea"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "58a57f5c1ca24cc91c54bd0e41377f361168c2579dd2bff52c7c80fee44b1124"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "ae152974d1424f8afb12dc558c0322615f7d3036"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "77783bd1d7636ad441ec769d933102561d2586c96e4717e2e4c71dec732dafde"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "d7782b996cceed60fd94eff920280fdd26820e02"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "07cc45b7377234883323ae1ca4b4931eec0220419ec6a011434b04227d4275d6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "9e0441dfbe0d144b6f8b438c9f84abe1fd2bd615"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "9b05ab6d33f86430624b4c0657cf2f1b002486df40aa5f4680856af1bc39e5cf"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "280bb18cfcfe8044de06cba291fca502efd1c948"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a3505375563927b72164f7bc13e03bd3598794946acb465a55e0ee1203ea4ed9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "0f0d2a7d289a3544c8164e5dc0de8e78838fa4c9"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "61228cc3b21d37e21456d6f1bc2ba9e2926b9e154abe538ef1460748abd3e3d0"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "000cf1ce776f90f419f9d0ee8030163c2f91e9c8"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "20b503529584e793333638558a666cae716e542c704842cfc8be1b063ccb4721"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "5e1f03359de006a1b432d59f6d20b87fbbcb72c2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d265c3e818ad38171e19d34e9956210199e9a74cf7eba7e22e9deb1b4c2efe3a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "ef93ec50071e96a92b944e688a09dce6169d5763"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "16a7b33d40ae4919773e28c33ed249fc69fece33b8eaed15c7c2857c59564102"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "7da172ffa81fb11f9954017e29baecfc1e38e512"
libgfortran_version = "4.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "975f0e85e14b41a3054fd8e83a2414d04121cc65bdaf385b97c06cb5967683e4"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "ed01359c33510c7216e71fd981b02bd88b3f1681"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "b611f6d39c751e7b09de903e407a646f01004e9953f2031f9d0e8047fd692151"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.0+0/CompilerSupportLibraries.v0.3.0.i686-linux-musl-libgfortran4.tar.gz"
