[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "fe99e480f5a020ffb7b42c21adda6d4879ff03b4"
libgfortran_version = "3.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "9470d3fee2c22480b68a8207d87804bed0701a4b1d53de26c57e2ddd6c628db7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "2c59ae2f8a812638140e06f6d1d4e732404a22ee"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "25ed225d31ec389ce65cd839c0ddb41e1c96dfc2dfa9f72b16476b5f13c520b2"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "7d37563affbfb4292510de1ccc69a8efdbe46ddc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "5c92b183b1eaa2134b6b9a761ed34d95b1c534ac8d904a75c07260eef3ad34f9"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "eb936be3afd154f4b18c71af8d22780b6b518354"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "971ad180ddb47fa77dd93380b1d41b2f51cd81034c802177b0e074101b7cbdbb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "fde010ad5a8909d9c83e8b43b291f26da9ff7bcf"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "216716379491e7bd27a538e7bd65cdb4bbbc0faef69a14ecebde01ff644fa110"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "94b4b33b5b4552eda2e45545d33050b312248749"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "05873fff14de80cd287869ced04b3056994b76db5d6cc6944960389a2987333f"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "21c77ada5bb29a44fdd41c729097e906d28ac9aa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "43c0caf2338f137614747681b3c236031d198fd01b8020bda3bcbad795934f2a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "9edc64e0d45318e733e092e0c637e46e198620ae"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "e5f3cdfdfa55897da3456200974b14ea164e1ec6e596de9070b774e8a06137d5"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "c1313de0a275e8adc7a016092fbdc5f7d60a67ae"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "a6d56bf6f25df847c10ee27a99c9d6dab8e50cf484773355d358ad032295fc07"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "f5869b5aec37a5b09dfb4b558012306e6d9ae10f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "2168776c952d4fdb6cbce69306c5f3cade262b11b329aad63d8578abdee14310"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "7d75120b68b8c62549d18fd6b7fab7444efa1d3d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d9865f3c95033736f3889360fcae6df5d2c981901a55a0e43dc1aea2b26e991d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "5a3d9e1060ef33f4e6f64829c471bf1db040540b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "38d5ff4198897e386286f6ec8dca30065276009209e7df61480754f799a62bbd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "20180ee0424583c851f33f86ada3624f8154675f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "243299c62fd437bdd6308238fd5c7e31524dcfc0623b8d12398bdc75772918c6"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "6a274f5c0d0247594473b8cb56bb82079ef25ec8"
libgfortran_version = "4.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "015de1709819203b3a24ed9c6f2f9239841aa943e00ffd9be27eb54a949cc92b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "584e64ba5b87ca7ead328e88d4347b65b37ebba4"
libgfortran_version = "5.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "3293a11cc7d21b8a1c571f339dcf34f587ff4fc280d4297b772d865fbbaf9341"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "7c6721ada3c7a48d3523042943a19284fdcb0fc0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "20b5a210d0178d9103210c560509da242ff13012129f9cc366fef448af645629"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "7a1468d950629bb5c197887f40fdc2aea1ea60a4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "6735b97645cf078abe632f7b5dca083fcb571e970762b97c38cfce13cfde1585"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "07ef7b5fc5d5f76756b5f7b8b516134af22c5d45"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "dd2244ba33626cd0b74df358dea38889b834669c91ab11695cfa6c3fe80375dd"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "998210f01fc6f86c57554d5d0ac4a6a73e2683cd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ef3a4694257869173ead515527b0cc5a02607fb811462cd5117349111cf5eeb7"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "fec7f05fc2e9330029dea5b7564342c67075edfb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "d558ddcbf906be3062f75cf0dd1b2858258da0dce7da4e6cafc07ffcc790d241"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "e22c450951a40bf9b7d9a0c93049fe69ce01014f"
libgfortran_version = "5.0.0"
os = "macos"

    [[CompilerSupportLibraries.download]]
    sha256 = "de8181f05e14e0de08e74a833e0fc8ffc44c2addbc8b8883e78770e120d0599d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "97117d92aa61124159b860d6b799b8c623ace9f8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "fb734afc67da857e74c4c47e08154e5adeaaa4299ec871877e3e6a471fd62f30"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "29f5dbde195b3d151aff3f73794329cff0cc7096"
libgfortran_version = "4.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "4f0096ec6d3f2563ca2782816dc54ab98645ac271713bcea7962ca679b92505d"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "armv7l"
git-tree-sha1 = "d152ab0ab022fa7b4c1e2972e24392739b9f1550"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "4ffa566079f769f79e78ba87212c74ff4bf4f6064bd6bef33c26983eb8cf9b29"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "8d20eeae829fd4fb1c6c4938b0f8c5496b2cc29d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "bb749bcffb9f91cb11cf18bb0b47521c1d32c33255e958cc3680aa699309b18e"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "ac5f9f4d40d7173f2b6535a2042f64d30a02dc5e"
libgfortran_version = "3.0.0"
os = "windows"

    [[CompilerSupportLibraries.download]]
    sha256 = "703fb4f8c49b53b922321ab5c54ce825e2a56444bd240f0fbcc8c4f4e65d482a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "9c80dde139355329e4d2a79f4e7190b5ed9bc40f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "cbf40bd0f6dd91d3f358f05ca09c83c85fec69fb5ff2daad2a0390adb45da879"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "powerpc64le"
git-tree-sha1 = "876d74371d5f0f8313dfc35fd6dbf6902f6f27be"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "706a0c440bda79225ff4394110619ccf05689d61d983c206021f7e875d299523"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "92229d83ec9fc68581af133eb83e7378a442ed10"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "024bbbf3822f886c4f7597e411cc0654ad6d1234b5f761e86438bbedd5be8ef4"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "d90ecbe7003ee711cd42d0549770dd0ad63dc6b9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "ddf8cfa637a0941607e36458179d284d9215f569eab39fe87ac6477ae46d0acb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "b2b1ba100d3f959776019d28d682ab8b579c2648"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "088ba172f57ab80235c6d73d7b6492e98cc1e6f186e51473efc9c88290882d06"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "eb3dbc96a8532b1e19239b0da1e99ebfb772b19f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "93fa454f8296d591f79965850c287bf8f3eab5646b23ae58217333f94dbc960a"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-gnu-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "i686"
git-tree-sha1 = "216f60bbcfb0973397787248ca8ec9358f17231f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "21395e0fcd2245493760c76ad258c5d7769c202ad6372ee78b4905d19577cf2b"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.i686-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "006c70503895dd0680ffb2abd32c622e25e97f26"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "76d34b00be214d0121eb56e8d5b708df4dcaa65c1c0fc32f99d7242c3ee20380"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "1c861fe2f4a42beb099588fd6f0fae86982baa39"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "c321a0a0a90636af51ac6b935c5bd82b6bca548570748545b75c22bebc6e9abb"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "5f081f746de52463093ebfba4514e6778517ea6e"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "42aa04fbe277dea9bafb72722118d6c2309fcbd88d361fdf61d49aeb3a895125"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "aarch64"
git-tree-sha1 = "7d6c8925e6f960bd54b06447262b47743b89cf5e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[CompilerSupportLibraries.download]]
    sha256 = "59c4a85fd7fac8b550a0427ad9833de68b46e857cdcaddf57470ac96a7d396c1"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "49b0f69839879c1f6c78c4141297e6ebfd6af556"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "65b387278b413c33cb0fd6cbaec48da7871001ef958aa79691a26e367b520484"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[CompilerSupportLibraries]]
arch = "x86_64"
git-tree-sha1 = "cfc8b893e798e1afb17b01e961c8669d819a6254"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[CompilerSupportLibraries.download]]
    sha256 = "18b210a380524e839b4e6beeaf1114c1836dd63eb3eca33d400a4ac658409d66"
    url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.2+0/CompilerSupportLibraries.v0.3.2.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
