# Autogenerated wrapper script for CompilerSupportLibraries_jll for i686-w64-mingw32-libgfortran5
export crtbegin_o, crtend_o, dllcrt2_o, libadvapi32_a, libatomic, libgcc_a, libgcc_s, libgcc_s_a, libgfortran, libgomp, libmingw32_a, libmoldname_a, libmsvcrt_a, libpthread_dll_a, libshell32_a, libssp, libssp_dll_a, libstdcxx, libuser32_a

JLLWrappers.@generate_wrapper_header("CompilerSupportLibraries")
JLLWrappers.@declare_file_product(crtbegin_o)
JLLWrappers.@declare_file_product(crtend_o)
JLLWrappers.@declare_file_product(dllcrt2_o)
JLLWrappers.@declare_file_product(libadvapi32_a)
JLLWrappers.@declare_library_product(libatomic, "libatomic-1.dll")
JLLWrappers.@declare_file_product(libgcc_a)
JLLWrappers.@declare_library_product(libgcc_s, "libgcc_s_sjlj-1.dll")
JLLWrappers.@declare_file_product(libgcc_s_a)
JLLWrappers.@declare_library_product(libgfortran, "libgfortran-5.dll")
JLLWrappers.@declare_library_product(libgomp, "libgomp-1.dll")
JLLWrappers.@declare_file_product(libmingw32_a)
JLLWrappers.@declare_file_product(libmoldname_a)
JLLWrappers.@declare_file_product(libmsvcrt_a)
JLLWrappers.@declare_file_product(libpthread_dll_a)
JLLWrappers.@declare_file_product(libshell32_a)
JLLWrappers.@declare_library_product(libssp, "libssp-0.dll")
JLLWrappers.@declare_file_product(libssp_dll_a)
JLLWrappers.@declare_library_product(libstdcxx, "libstdc++-6.dll")
JLLWrappers.@declare_file_product(libuser32_a)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        crtbegin_o,
        "lib\\gcc\\i686-w64-mingw32\\14\\crtbegin.o",
    )

    JLLWrappers.@init_file_product(
        crtend_o,
        "lib\\gcc\\i686-w64-mingw32\\14\\crtend.o",
    )

    JLLWrappers.@init_file_product(
        dllcrt2_o,
        "lib\\gcc\\i686-w64-mingw32\\14\\dllcrt2.o",
    )

    JLLWrappers.@init_file_product(
        libadvapi32_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libadvapi32.a",
    )

    JLLWrappers.@init_library_product(
        libatomic,
        "bin\\libatomic-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libgcc_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libgcc.a",
    )

    JLLWrappers.@init_library_product(
        libgcc_s,
        "bin\\libgcc_s_sjlj-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libgcc_s_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libgcc_s.a",
    )

    JLLWrappers.@init_library_product(
        libgfortran,
        "bin\\libgfortran-5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgomp,
        "bin\\libgomp-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libmingw32_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libmingw32.a",
    )

    JLLWrappers.@init_file_product(
        libmoldname_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libmoldname.a",
    )

    JLLWrappers.@init_file_product(
        libmsvcrt_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libmsvcrt.a",
    )

    JLLWrappers.@init_file_product(
        libpthread_dll_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libpthread.dll.a",
    )

    JLLWrappers.@init_file_product(
        libshell32_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libshell32.a",
    )

    JLLWrappers.@init_library_product(
        libssp,
        "bin\\libssp-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libssp_dll_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libssp.dll.a",
    )

    JLLWrappers.@init_library_product(
        libstdcxx,
        "bin\\libstdc++-6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libuser32_a,
        "lib\\gcc\\i686-w64-mingw32\\14\\libuser32.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
