# Autogenerated wrapper script for CompilerSupportLibraries_jll for x86_64-w64-mingw32-libgfortran5
export crt2_o, crt2u_o, crtbegin_o, crtend_o, dllcrt2_o, libadvapi32_a, libatomic, libdbghelp_a, libgcc_a, libgcc_s, libgcc_s_a, libgfortran, libgomp, libiphlpapi_a, libkernel32_a, libmingw32_a, libmingwex_a, libmoldname_a, libmsvcrt_a, libmsvcrt_os_a, libntdll_a, libole32_a, libpsapi_a, libpthread_dll_a, libsecur32_a, libshell32_a, libssp, libssp_a, libssp_dll_a, libstdcxx, libuser32_a, libuserenv_a, libuuid_a, libwinmm_a, libws2_32_a

JLLWrappers.@generate_wrapper_header("CompilerSupportLibraries")
JLLWrappers.@declare_file_product(crt2_o)
JLLWrappers.@declare_file_product(crt2u_o)
JLLWrappers.@declare_file_product(crtbegin_o)
JLLWrappers.@declare_file_product(crtend_o)
JLLWrappers.@declare_file_product(dllcrt2_o)
JLLWrappers.@declare_file_product(libadvapi32_a)
JLLWrappers.@declare_library_product(libatomic, "libatomic-1.dll")
JLLWrappers.@declare_file_product(libdbghelp_a)
JLLWrappers.@declare_file_product(libgcc_a)
JLLWrappers.@declare_library_product(libgcc_s, "libgcc_s_seh-1.dll")
JLLWrappers.@declare_file_product(libgcc_s_a)
JLLWrappers.@declare_library_product(libgfortran, "libgfortran-5.dll")
JLLWrappers.@declare_library_product(libgomp, "libgomp-1.dll")
JLLWrappers.@declare_file_product(libiphlpapi_a)
JLLWrappers.@declare_file_product(libkernel32_a)
JLLWrappers.@declare_file_product(libmingw32_a)
JLLWrappers.@declare_file_product(libmingwex_a)
JLLWrappers.@declare_file_product(libmoldname_a)
JLLWrappers.@declare_file_product(libmsvcrt_a)
JLLWrappers.@declare_file_product(libmsvcrt_os_a)
JLLWrappers.@declare_file_product(libntdll_a)
JLLWrappers.@declare_file_product(libole32_a)
JLLWrappers.@declare_file_product(libpsapi_a)
JLLWrappers.@declare_file_product(libpthread_dll_a)
JLLWrappers.@declare_file_product(libsecur32_a)
JLLWrappers.@declare_file_product(libshell32_a)
JLLWrappers.@declare_library_product(libssp, "libssp-0.dll")
JLLWrappers.@declare_file_product(libssp_a)
JLLWrappers.@declare_file_product(libssp_dll_a)
JLLWrappers.@declare_library_product(libstdcxx, "libstdc++-6.dll")
JLLWrappers.@declare_file_product(libuser32_a)
JLLWrappers.@declare_file_product(libuserenv_a)
JLLWrappers.@declare_file_product(libuuid_a)
JLLWrappers.@declare_file_product(libwinmm_a)
JLLWrappers.@declare_file_product(libws2_32_a)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        crt2_o,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\crt2.o",
    )

    JLLWrappers.@init_file_product(
        crt2u_o,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\crt2u.o",
    )

    JLLWrappers.@init_file_product(
        crtbegin_o,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\crtbegin.o",
    )

    JLLWrappers.@init_file_product(
        crtend_o,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\crtend.o",
    )

    JLLWrappers.@init_file_product(
        dllcrt2_o,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\dllcrt2.o",
    )

    JLLWrappers.@init_file_product(
        libadvapi32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libadvapi32.a",
    )

    JLLWrappers.@init_library_product(
        libatomic,
        "bin\\libatomic-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libdbghelp_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libdbghelp.a",
    )

    JLLWrappers.@init_file_product(
        libgcc_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libgcc.a",
    )

    JLLWrappers.@init_library_product(
        libgcc_s,
        "bin\\libgcc_s_seh-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libgcc_s_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libgcc_s.a",
    )

    JLLWrappers.@init_library_product(
        libgfortran,
        "bin\\libgfortran-5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgomp,
        "bin\\libgomp-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libiphlpapi_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libiphlpapi.a",
    )

    JLLWrappers.@init_file_product(
        libkernel32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libkernel32.a",
    )

    JLLWrappers.@init_file_product(
        libmingw32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libmingw32.a",
    )

    JLLWrappers.@init_file_product(
        libmingwex_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libmingwex.a",
    )

    JLLWrappers.@init_file_product(
        libmoldname_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libmoldname.a",
    )

    JLLWrappers.@init_file_product(
        libmsvcrt_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libmsvcrt.a",
    )

    JLLWrappers.@init_file_product(
        libmsvcrt_os_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libmsvcrt-os.a",
    )

    JLLWrappers.@init_file_product(
        libntdll_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libntdll.a",
    )

    JLLWrappers.@init_file_product(
        libole32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libole32.a",
    )

    JLLWrappers.@init_file_product(
        libpsapi_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libpsapi.a",
    )

    JLLWrappers.@init_file_product(
        libpthread_dll_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libpthread.dll.a",
    )

    JLLWrappers.@init_file_product(
        libsecur32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libsecur32.a",
    )

    JLLWrappers.@init_file_product(
        libshell32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libshell32.a",
    )

    JLLWrappers.@init_library_product(
        libssp,
        "bin\\libssp-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libssp_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libssp.a",
    )

    JLLWrappers.@init_file_product(
        libssp_dll_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libssp.dll.a",
    )

    JLLWrappers.@init_library_product(
        libstdcxx,
        "bin\\libstdc++-6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libuser32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libuser32.a",
    )

    JLLWrappers.@init_file_product(
        libuserenv_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libuserenv.a",
    )

    JLLWrappers.@init_file_product(
        libuuid_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libuuid.a",
    )

    JLLWrappers.@init_file_product(
        libwinmm_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libwinmm.a",
    )

    JLLWrappers.@init_file_product(
        libws2_32_a,
        "lib\\gcc\\x86_64-w64-mingw32\\14\\libws2_32.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
