# Autogenerated wrapper script for CompilerSupportLibraries_jll for x86_64-linux-musl-libgfortran5
export crtbeginS_o, crtendS_o, crti_o, crtn_o, libatomic, libgcc_a, libgcc_s, libgfortran, libgomp, libstdcxx

JLLWrappers.@generate_wrapper_header("CompilerSupportLibraries")
JLLWrappers.@declare_file_product(crtbeginS_o)
JLLWrappers.@declare_file_product(crtendS_o)
JLLWrappers.@declare_file_product(crti_o)
JLLWrappers.@declare_file_product(crtn_o)
JLLWrappers.@declare_library_product(libatomic, "libatomic.so.1")
JLLWrappers.@declare_file_product(libgcc_a)
JLLWrappers.@declare_library_product(libgcc_s, "libgcc_s.so.1")
JLLWrappers.@declare_library_product(libgfortran, "libgfortran.so.5")
JLLWrappers.@declare_library_product(libgomp, "libgomp.so.1")
JLLWrappers.@declare_library_product(libstdcxx, "libstdc++.so.6")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        crtbeginS_o,
        "lib/gcc/x86_64-linux-musl/15/crtbeginS.o",
    )

    JLLWrappers.@init_file_product(
        crtendS_o,
        "lib/gcc/x86_64-linux-musl/15/crtendS.o",
    )

    JLLWrappers.@init_file_product(
        crti_o,
        "lib/gcc/x86_64-linux-musl/15/crti.o",
    )

    JLLWrappers.@init_file_product(
        crtn_o,
        "lib/gcc/x86_64-linux-musl/15/crtn.o",
    )

    JLLWrappers.@init_library_product(
        libatomic,
        "lib/libatomic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libgcc_a,
        "lib/gcc/x86_64-linux-musl/15/libgcc.a",
    )

    JLLWrappers.@init_library_product(
        libgcc_s,
        "lib/libgcc_s.so.1",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgfortran,
        "lib/libgfortran.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgomp,
        "lib/libgomp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libstdcxx,
        "lib/libstdc++.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
